### ISSUE TITLE
flirt function identification

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa#435]
https://github.com/fireeye/capa/discussions/414#discussioncomment-342159

use open source FLIRT implementation to identify functions.

signature distribution is an open problem.

TODO: 
  - [x] consider moving into viv-utils 358aab85e7da4e502497e73542392cf311c3393c
  - [x] cleanup integration/API f2c95568bdbb6a8673f310fbfa01247f22131277
  - [x] specify signature set path via cli f2c95568bdbb6a8673f310fbfa01247f22131277
  - [x] fix python-flirt loading `1.pat` signature file https://github.com/williballenthin/lancelot/commit/881aba96749eab0f396464b5b03e0e878a2ac718
  - [x] add comments support to python-flirt so we can embed licenses https://github.com/williballenthin/lancelot/commit/a8c6a8e91177cdd5b7099ab57862796b552ee6a5
  - [x] detect and support gz-compressed pat files 004ddb3e66182450727488dd4994c3cc41f3ee6c
  - [x] al-khaser x86 performance #448
  - [x] new python-flirt release https://github.com/williballenthin/lancelot/releases/tag/v0.5.5
  - [x] bump python-flirt dep https://github.com/williballenthin/viv-utils/commit/194ea7514754751c8935d03ede859208a779fcee
  - [x] new viv-utils release https://github.com/williballenthin/viv-utils/releases/tag/v0.4.1
  - [x] bump viv-utils dep 1e8161b24e5680924b780fbb21ab4d3ccd1066e2
  - [x] configure default signature set https://github.com/fireeye/capa/pull/446/commits/ff8a6f1d570c4b7fe154c8948bbee9db76160880
  - [x] embed signature set in pyinstaller exe https://github.com/fireeye/capa/pull/446/commits/30e1d409dd0d728d1bc3e7eadd50c3d5e5172974
  - [x] verify FLIRT native lib works in pyinstaller exe #452 https://github.com/fireeye/capa/runs/2043611001
  - [x] refactor cli argument parsing #449 #450
  - [x] code style
  - [x] viv-utils needs to be py2 compatible (remove type annotations)
  - [x] new viv-utils release
  - [x] bump viv-utils dep
  - [x] collect re-distributable signature set fc12645
  - [x] add licenses to signature set 9a28279

**Comment by williballenthin** [comment]
working branch: https://github.com/fireeye/capa/tree/function-id-flirt

**Comment by williballenthin** [comment]
some initial results:

FLIRT matching works well to find library functions. I've been using PMA 16-01.exe as my test sample, and using `vc32rtf.sig` as IDA would finds 104 of 172 total functions. this means that capa only has to match against the remaining 70 functions, limiting the potential for FPs.

however, the FLIRT matcher performance is not as good as I'd have hoped:

no FLIRT: ~12s
using [libcmt_15_msvc_x86.pat](https://github.com/Maktm/FLIRTDB/blob/1f5763535e02d7cccf2f90a96a8ebaa36e9b2495/cmt/windows/libcmt_15_msvc_x86.pat) with ~400 signatures: ~12s
using `vc32rtf.sig` with ~60,000 signatures: ~19s

in the former cases, FLIRT matching is negligible, and capa matching takes about 8 seconds.
in the latter case, FLIRT matching takes a full 10 seconds, and then does capa matching in about 2 seconds.

as i play with the number of rules compiled and matched, they affect matching runtime linearly (more rules, more FLIRT matching time).

the takeaway: FLIRT matching using all known signatures won't be a magic bullet to improve capa performance. it can still reduce the chance for FP.

---

that being said, blindly throwing hundreds of thousands of FLIRT signatures against the binary isn't the only way to go. for capa, we're mostly worried about functions that we know can FP against our rules. so, we could cut down the signature set to functions we actually care about.

couple strategies:
  1. manually curate the functions we want to ignore
  2. run capa against known libraries and include signatures for any functions that match
  3. scan a large number of binaries, do frequency analysis, figure out which functions FP, and then include those signatures

**Comment by williballenthin** [comment]
FLIRT matching would parallelize really well, except we're in Python-land.

**Comment by williballenthin** [comment]
I benchmarked the `RegexSet` implementation versus a naive "for each regex, match" implementation and they come out similar:

```
regexset/haystacks/100/patterns/all
                        time:   [1.9270 s 1.9420 s 1.9584 s]
regexset/haystacks/all/patterns/all
                        time:   [2.9924 s 3.0643 s 3.1482 s]
regexset/haystacks/100/patterns/0
                        time:   [1.0851 us 1.1215 us 1.1940 us]
regexset/haystacks/100/patterns/1
                        time:   [4.7519 us 4.8625 us 4.9494 us]
regexset/haystacks/100/patterns/10
                        time:   [5.5077 us 5.5938 us 5.6995 us]
regexset/haystacks/100/patterns/100
                        time:   [6.2007 us 6.2727 us 6.3416 us]
regexset/haystacks/100/patterns/1000
                        time:   [9.0068 us 9.2327 us 9.4902 us]
regexset/haystacks/100/patterns/10000
                        time:   [329.04 ms 330.91 ms 333.13 ms]
regexset/haystacks/100/patterns/34503
                        time:   [1.6432 s 1.6584 s 1.6745 s]

multiregex/haystacks/100/patterns/all
                        time:   [1.3020 s 1.3068 s 1.3117 s]
multiregex/haystacks/all/patterns/all
                        time:   [2.2366 s 2.2523 s 2.2682 s]
multiregex/haystacks/100/patterns/0
                        time:   [491.14 ns 492.26 ns 493.67 ns]
multiregex/haystacks/100/patterns/1
                        time:   [1.8773 us 1.9121 us 1.9511 us]
multiregex/haystacks/100/patterns/10
                        time:   [48.319 us 49.473 us 50.620 us]
multiregex/haystacks/100/patterns/100
                        time:   [401.53 us 408.76 us 417.90 us]
multiregex/haystacks/100/patterns/1000
                        time:   [9.5294 ms 9.6405 ms 9.7659 ms]
multiregex/haystacks/100/patterns/10000
                        time:   [354.91 ms 357.09 ms 359.36 ms]
multiregex/haystacks/100/patterns/34503
                        time:   [1.3425 s 1.3539 s 1.3644 s]
```

The multi regex solution uses about 4x more memory, but performs slightly better when the entire signature set. In any case, its not 10x faster or slower. Need to keep looking for optimizations.

**Comment by williballenthin** [comment]
after some brainstorming and implementation, i've made FLIRT matching much faster. like 10,000x faster!

the key insight are that:
  1. matches are *always* anchored at the start of the haystack, and
  2. the haystack is small (fits in cache/RAM)

therefore, during matching we can probe forward and backwards in the haystack. in contrast, regular expressions match strictly iteratively from the first to last byte.

we build a decision tree that selects the patterns that may match a haystack. each node in the tree checks the haystack value at a particular index and branches to children nodes. the leaf nodes contain the candidate patterns that could match the haystack. they are validated via a naive (masked) memcmp. the branching factor of each node is often quite high - dozens or so. therefore, we can pick the best set patterns to check in just a few probes of the haystack.

the decision tree size is on the order of a few megabytes for the 30k pattern `vc32rtf` set. the regex-based implementation took hundreds of MBs.

benchmarks:

```
decision tree/haystacks/100/patterns/all
                        time:   [16.508 us 16.890 us 17.724 us]
decision tree/haystacks/all/patterns/all
                        time:   [29.761 us 30.134 us 30.878 us]
decision tree/haystacks/100/patterns/0
                        time:   [509.43 ns 547.29 ns 573.25 ns]
decision tree/haystacks/100/patterns/1
                        time:   [2.7011 us 2.9990 us 3.3060 us]
decision tree/haystacks/100/patterns/10
                        time:   [1.9253 us 1.9411 us 1.9656 us]
decision tree/haystacks/100/patterns/100
                        time:   [4.1463 us 4.1818 us 4.2301 us]
decision tree/haystacks/100/patterns/1000
                        time:   [8.2514 us 8.3054 us 8.3693 us]
decision tree/haystacks/100/patterns/10000
                        time:   [13.160 us 13.365 us 13.638 us]
decision tree/haystacks/100/patterns/34503
                        time:   [17.885 us 18.314 us 18.717 us]
```

**Comment by williballenthin** [comment]
with new FLIRT backend, we see performance against PMA 16-01.exe like:

```
DEBUG:capa.features.extractors.viv:perf: flirt: parsing .sig: vc32rtf.sig: 0.13s
DEBUG:capa.features.extractors.viv:flirt: sig count: 60195
DEBUG:capa.features.extractors.viv:perf: flirt: compiling sigs: 0.39s
...94 recognized library functions...
DEBUG:capa.features.extractors.viv:perf: flirt: matching sigs: 0.02s
```

then capa matching against the remaining 75 functions in ~4 seconds for a total runtime of ~6.5s total. when i disable FLIRT signatures, total runtime is ~12s. that's a speedup of around 1.8x!

**Comment by williballenthin** [comment]
the old implementation matched 104 functions while the new implementation matches 94. need to look into that.

before/after: https://gist.github.com/williballenthin/0f6b10b2fe1937ffa0961c62df959df0

**Comment by williballenthin** [comment]
with fixes from https://github.com/williballenthin/lancelot/issues/112, PMA16-01 is up to 141 matches against vc32rtf. there are only 189 functions total.

**Comment by williballenthin** [comment]
closed in #446
